name:  tutorialsamples
description:  A sample application
environment:
  sdk: any
dependencies:
  oauth2: any
  http: any
  pathos: any
  hop: any
  browser: any
#  web_ui:
#    git: https://github.com/dart-lang/web-ui.git
  web_ui: any
