name: async_await_catch_error
description: A sample application that reads a file on dartlang using async/await, and prints the contents; errors are caught.
homepage: https://dart.dev/tutorials/language/futures

environment:
  sdk: '>=2.3.0 <3.0.0'

dev_dependencies:
  build_runner: ^1.5.0
  build_web_compilers: ^2.1.0
  pedantic: ^1.7.0
